sudo: false

branches:
  only:
    - master

addons:
  apt:

script:
  - wget -O - "http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.15.linux.bin.tar.gz" | tar xz -C ${TMPDIR-/tmp} doxygen-1.8.15/bin/doxygen
  - cd doc
  - ../doxygen-1.8.15/bin/doxygen --version
  - ../doxygen-1.8.15/bin/doxygen Doxyfile

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: doc/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
