# This is a basic workflow to help you get started with Actions

name: Doxygen build&deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with: 
          path: JKQtPlotter
            
      - name: Install dependencies
        run: |
             sudo apt-get update
             sudo apt-get update --fix-missing
             sudo apt-get install -f
             sudo apt -y install build-essential doxygen graphviz doxygen-latex

      - name: Run Doxygen
        run: |
          cd doc
          doxygen --version
          doxygen Doxyfile
          echo "" > html/.nojekyll
          cd ..
 
      - uses: DenverCoder1/doxygen-github-pages-action@v1
        with:
          github_token: ${{ secrets.GH_PAGES_SECRET }}
          branch: gh-pages
          folder: docs/html
          
